### ISSUE TITLE
Hashing to form storageStruct ID's?

### ISSUE THREAD

**Issue by Scrubsauce** [mindaptiv/Ellen#116]
The way we're retrieving storageStruct info does not enumerate the device paths in any special way (except for those instances of MTP USB stuff).  I've set the string_id field of these structs to be the path to access that storage space in the filesystem, and set the int_id field of these structs to a default ERROR_INT value defined in cylon.h.  

Possible solutions I've come up with are to either assume going in on Ellen that the storageStructs won't usually have an int_id (not appealing to me, but that's how it is as of this latest push), OR to possibly hash the path into some sort of hex value to store as a unique ID.  I've never dealt with any hashing algorithms though and was looking for guidance on if this is even needed or if there is a light weight hashing method (possibly even in libc or libstdc++?) that you're aware of that would fit this use case?

**Comment by Simulacrum0** [comment]
#0) Sorry on delayed replies...i missed this from Mon. and then had medical-scanning day of complexities...so am back to clean up all remaining items!

#1) Plenty of Hashtable implementations out there...its called "Map" in STL...and if you make a key, such as the Pathstring you mentioned above, or that plus some other data-details ( really doesn't matter, its just an array of bits that get 'transformed' mathematically, into some number that is truncated to N bits, like 64, for bins.  Whether called "Map" or "Dictionary" or "Lookup Table" or Associative Array, there are lots of solutions to use.  I'd recommend using the "C" code from Python ( yes, Python is written as C to bootstrap their API )  Here's the implementation:  http://svn.python.org/projects/python/trunk/Objects/dictobject.c

Of course many choices are out there...but the challenges mostly surround how you generate the 'hash IDs' themselves and how you resolve collisions ( when two names, such as two storage-device paths, transform into the same 'hash-bin' ).  Usually linked-list or more hashing is used.  Lemme know if you get stuck there??

**Comment by Scrubsauce** [comment]
Willco, shift to Marrow for now.  

Benefit of having a string id and an int id in our deviceStructs is that since the string id is based on the path for this device it should still be unique for all devices of type STORAGE_TYPE.

**Comment by Scrubsauce** [comment]
*Shift to Sinew.
