### ISSUE TITLE
libdl is not part of the LSB?

### ISSUE THREAD

**Issue by Scrubsauce** [mindaptiv/Ellen#26]
If we are assuming we're safe for anything included in the LSB, but then want to use dlfcn.h (libdl) to load stuff that is not considered standardized across all the OS falvors, isn't that some sort of a logical fallacy?  We can't dlopen() the library that defines dlopen(), and wouldn't we run into issues on the off chance we install on a system that does not have libdl on it?  (have done some research and am not seeing dlfcn being included as part of libc)

**Comment by Simulacrum0** [comment]
Good question...seems like we have to statically link libdl always ( bootstrap paradigm! ). Dlopen/Dlsym gotta be there or nothing else works.  So include the header, add the lib to the makefile/IDE-project, and static-symbol-linkage should do the trick as usual.
