### ISSUE TITLE
Ellen Barebones Log Example

### ISSUE THREAD

**Issue by Scrubsauce** [mindaptiv/Ellen#34]
For your reference: 

`Cylon @: 0x7ffcd3fd9590`
`Username: mindmin`
`Device Name: mindmin-MacPro`
`Timestamp: 3, 7/3/2015 12:27:24:0 MDT -360 DST: 1`
`Profile Picture Location: /var/lib/AccountsService/icons/mindmin Type: .png`
`Processor Architecture: x86_64`
`Processor Level: 44`
`Processor Count: 24`
`Processor Clock Speed: 1.596e+09Hz`
`OS Architecture: 64`
`Installed Memory: 12588351488`
`Available Memory: 8516747264`
`Low Memory Threshold: 12462468096`
`Low Memory? 0`
`Page Size: 4096`
`Allocation Granularity: 4096`
`Min/Max App Address: 0/0`
`Error: 0`

**Comment by Simulacrum0** [comment]
Cool-
Have a great trip/move/adventures...
