### ISSUE TITLE
Controller/Gamepad producer

### ISSUE THREAD

**Issue by Scrubsauce** [mindaptiv/Ellen#55]

**Comment by Scrubsauce** [comment]
![20150812_123941](https://cloud.githubusercontent.com/assets/2531841/9233336/b6d6cdba-40ef-11e5-848a-59b39416bfd0.jpg)

**Comment by Scrubsauce** [comment]
![20150812_123941](https://cloud.githubusercontent.com/assets/2531841/9233352/c77b10ae-40ef-11e5-94ba-c649e4680ad9.jpg)

**Comment by Scrubsauce** [comment]
![crossplatform-game-engine-development-with-sdl-20-23-638](https://cloud.githubusercontent.com/assets/2531841/9234491/5b4f99de-40f6-11e5-9e3e-0910b7deb672.jpg)
http://image.slidesharecdn.com/sdl2-final-130908120219-/95/crossplatform-game-engine-development-with-sdl-20-23-638.jpg?cb=1386864970

**Comment by Scrubsauce** [comment]
https://wiki.libsdl.org/SDL_NumJoysticks

**Comment by Scrubsauce** [comment]
https://wiki.libsdl.org/CategoryGameController

**Comment by Scrubsauce** [comment]
Preliminary producer code for gamepad detection as of 71682e9d784a674757364567b54a8bc7da3f829a

**Comment by Scrubsauce** [comment]
Only driver install that worked for wireless 360 pads so far on Ubuntu that I've tried
http://www.omgubuntu.co.uk/2014/06/ubuntu-xbox-controller-support-xboxdrv-driver

**Comment by Scrubsauce** [comment]
Sees receiver as 4 controllers http://forums.libsdl.org/viewtopic.php?t=9766&sid=0924e5fcc26a2383131ddac0b245cd7c

**Comment by Scrubsauce** [comment]
Notes for Thursday-
1. Xbox One controllers continued to crash kernel, probably my machine, moving on (assuming on a machine where they work, SDL2 will capture them properly).  Upgrading to a stable kernel release failed to fix the issue, even when building the kernel by hand (various make commands in terminal on package files), Xbone pad would lock system (except for pointer mouse) and on reboot if still plugged in would prevent Ubuntu from starting up successfully.  Ugh.
2. Wii Motes worked with Wiican and showed up as a joystick device (though nunchuck was not present), but would not show up for SDL2 as a joystick OR gamecontroller object.  Assuming this is just settings in wiican and how I've paired it with machine.  Fiddled with it for about an hour but figured, again if someone gets it working properly on their own machine SDL2 will catch the device as a gamecontroller if its supported and move on.
3. Guitar Hero controller (from Guitar Hero 3 PC port) shows up specifically as a Red Octane Xplorer, though it works fine on Xbox 360's at parties, etc.  Curious why it would have its own drivers instead of just using a 360 pad driver.  However, SDL2 sees it as a joystick object but does NOT support it as a gamecontroller object.  Again, weird from where I'm sitting right now but I'm sure there's a reason for it all.  Still nice to see that not all joysticks are gamecontrollers (rectangles to squares analogy).

**Comment by Simulacrum0** [comment]
Ack!

**Comment by Scrubsauce** [comment]
@Simulacrum0 possible explanation since I'm using an opengl window instead of an SDL window? 
http://stackoverflow.com/questions/257275/no-sdl-keypress-events-being-detected

**Comment by Simulacrum0** [comment]
Hmmm, time to delve into the SDK source perhaps?  we need routines that can function on their own...no SDL window possible for us iirc?  TBD?

**Comment by Scrubsauce** [comment]
@Simulacrum0 
`If you set the environment variable SDL_VIDEODRIVER to the value "dummy" before intializing a video mode (or before SDL init?) the dummy video driver will be used and SDL_SetVideoMode will not create a window but you will still be able to use the functions that normally would require a window. Whether events will work or not I don't know.`

**Comment by Scrubsauce** [comment]
https://wiki.libsdl.org/SDL_WindowFlags
SDL_WINDOW_FULLSCREEN
fullscreen window
SDL_WINDOW_FULLSCREEN_DESKTOP
fullscreen window at the current desktop resolution
SDL_WINDOW_OPENGL
window usable with OpenGL context
SDL_WINDOW_SHOWN
window is visible
SDL_WINDOW_HIDDEN
window is not visible
SDL_WINDOW_BORDERLESS
no window decoration
SDL_WINDOW_RESIZABLE
window can be resized
SDL_WINDOW_MINIMIZED
window is minimized
SDL_WINDOW_MAXIMIZED
window is maximized
SDL_WINDOW_INPUT_GRABBED
window has grabbed input focus
SDL_WINDOW_INPUT_FOCUS
window has input focus
SDL_WINDOW_MOUSE_FOCUS
window has mouse focus
SDL_WINDOW_FOREIGN
window not created by SDL
SDL_WINDOW_ALLOW_HIGHDPI
window should be created in high-DPI mode if supported (>= SDL 2.0.1)
SDL_WINDOW_MOUSE_CAPTURE
window has mouse captured (unrelated to INPUT_GRABBED, >= SDL 2.0.4)

**Comment by Simulacrum0** [comment]
Seems unusually complicated to require Environment Variables instead of flags, as you provided later.  The flags indicate a decent range.  Questions i'd have are 

"Can we use this framework to capture/use all GPUs installed on all windows"?
"Any License/Shipping/Linux-variation issues"?

that's it for now...

**Comment by Scrubsauce** [comment]
Off the top of my head-
3-
`SDL 2.0 is freely available under the terms of the zlib license, and SDL 1.2 is freely available under the GNU LGPL license.`
`Both may be used in both free and commercial applications.`
`You can read the detailed license text at http://www.libsdl.org/license.php`

2-I've seen only a handful of issues from 2013 back related to FreeBSD users having some issues with certain parts of SDL, but nothing 2015+

1-SDL has a "design habit" of enumerating anything (controllers, drivers, etc.) as an integer, and then you can retrieve a specific "thing" via an int in that range (index lookup, etc.).

They do the same thing with Video stuff from what I've seen (note these are more drivers than a reference to a physical GPU, I'm guessing again here but I assume that's 'acceptable' because the driver handles the hardware?  Know about GPU's, experience in writing code for them is extremely limited so far so seeking to fill in the blanks as I go)-

`int SDL_GetNumVideoDrivers(void)`
`Use this function to get the number of video drivers compiled into SDL.`

`const char* SDL_GetVideoDriver(int index)`
`Returns the name of the video driver with the given index.`

`int SDL_GetNumVideoDisplays(void)`
`Use this function to return the number of available video displays.`

`const char* SDL_GetDisplayName(int displayIndex)`
`Use this function to get the name of a display in UTF-8 encoding.`

`int SDL_GetNumDisplayModes(int displayIndex)`
`Use this function to return the number of available display modes.`

`int SDL_GetDisplayMode(int              displayIndex,
                       int              modeIndex,
                       SDL_DisplayMode* mode)`
`Use this function to get information about a specific display mode.`

`int SDL_GetDisplayBounds(int       displayIndex,
                         SDL_Rect* rect)`
`Use this function to get the desktop area represented by a display, with the primary display located at 0,0.`

`typedef struct`
`{`
`Uint32 format;              /**< pixel format */`
`int w;                      /**< width */`
`int h;                      /**< height */`
`int refresh_rate;           /**< refresh rate (or zero for unspecified) */`
 `void *driverdata;           /**< driver-specific data, initialize to 0 */`
`} SDL_DisplayMode;`

Along with another good handful of getting other info about your current display and setting display settings, etc.  Its all handled in the SDL_video.h header file.
http://hg.libsdl.org/SDL/file/default/include/SDL_video.h
https://wiki.libsdl.org/CategoryVideo

Hopefully this fills in//alleviates some preliminary blanks/concerns?

There's a similar system for finding/loading/using audio drivers available on the system.
![swervestory](https://cloud.githubusercontent.com/assets/2531841/9819300/5f996412-586a-11e5-8508-45fd55c995ef.png)

**Comment by Scrubsauce** [comment]
Basic controller creation and button press detection (not storage) pushed w/ 8a234736c951a097e960488954872194cd8e17c4

**Comment by Scrubsauce** [comment]
SDL supports the Guide/Home button as a button (XINPUT does not).  However we are using the XINPUT style bit-mask on WIndows and Android (and now Linux) to store the button states.  

Thankfully there are 2 free spaces in the bit mask for now.  So will use one of these as the Guide/Home button and then expand to a 32 bit mask if XINPUT changes up its format someday.

**Comment by Scrubsauce** [comment]
Button press/release storage handled w/ 7c50477900456fe045cb6e4664b9c87faff13e60

**Comment by Scrubsauce** [comment]
Better button handling w/ ce6595738e64c74ee7ff0f61cf7d14eb7ce3ea87

**Comment by Scrubsauce** [comment]
Remaining things to capture-
-Triggers
-Joysticks
-Devices that are SDL_Joystick only + their inputs

**Comment by Simulacrum0** [comment]
Probably best to push it to a 32bit mask for buttons and move on for now...

> On 2015_Sep 14, at 12:48EDT, Josh Miller notifications@github.com wrote:
> 
> SDL supports the Guide/Home button as a button (XINPUT does not). However we are using the XINPUT style bit-mask on WIndows and Android (and now Linux) to store the button states.
> 
> Thankfully there are 2 free spaces in the bit mask for now. So will use one of these as the Guide/Home button and then expand to a 16 bit mask if XINPUT changes up its format someday.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/mindaptiv/Ellen/issues/55#issuecomment-140141712.

file:///.file/id=20807536.16777226 file:///.file/id=20807536.16777226

**Comment by Scrubsauce** [comment]
Changes from b33aab33e873a6cda1d26dc47c731f1e417758e3
- Event based button mask updating is now working for SDL_Joystick-based devices as well
- SDL_GameController-based devices now store their axes values on construction
- Added a controllerStruct builder that accepts SDL_Joystick data in place of SDL_GameController data

**Comment by Scrubsauce** [comment]
Changes from 897ef7a18011c94e0a1d8c6f197abff1cdcdebc1
- Event based axes values updating is now working for SDL_GameController devices
- controllerStruct buttons mask extended to 32-bits
- Added method to normalize SDL2 ranges to our Android-adopted ranges

TODO:
- Add normalization to controllerStruct builder method (currently only applied to event polling)
- Extend axes value capturing to SDL_Joystick devices

**Comment by Scrubsauce** [comment]
Normalization added to controllerStruct builder as of d81b2e17c143771b055b7c0a47024bf570002436

**Comment by Scrubsauce** [comment]
SDL_Joystick:

Old Xbox Axes Mapping:
- LX == 0
- LY == 1 
- LT == 2
- RX == 3
- RY == 4
- RT == 5

Old PS Style:
- LY == 0
- LX == 1
- RX == 3
- RY == 2
- Triggers not detected as axes events (maybe investigate further, might just be treated as buttons instead of axes?)

@Simulacrum0 since these devices are so sparse (or...old?  uncommonly used?  pre-2009?) inclined to just default to the Xbox mapping for axes UNLESS if a string-match happens on the joystick name for the phrases "dualshock" or "playstation" or "sony".

**Comment by Scrubsauce** [comment]
SDL_JoystickAxisEvents are now handled, with separate logic for Playstation-based devices and Xbox-based + other devices as of c2ab2aa8c9cd88cac18be6da6d79ebfa3eea110d

**Comment by Scrubsauce** [comment]
Guitar Hero RedOctane X-plorer now logs fully, including the internal tilting mechanism/"star power" activation feature on its own axis + whammy bar.

**Comment by Scrubsauce** [comment]
TODO: 
- handle SDL_GameController drop in/drop out #84 
- handle SDL_Joystick drop in/drop out #84 
- Xbox-based SDL_Joystick triggers go from a range of -32K to 32K instead of 0 to 32K like SDL_GameController.   Need to come up with a different normalization method for such devices to make them fall in line with our standards
- PS-based SDL_Joystick triggers do not register as (analog?) axis events, need to check button and hat event types to see how these are interpreted and then capture them correctly
- D-pad functionality via hat events for all SDL_Joystick devices still needs to be handled

**Comment by Scrubsauce** [comment]
Proper trigger normalization for SDL_Joystick devices that are not Playstation based as of 54878a6f460931726e8db72daa922d5c43853b7d

**Comment by Scrubsauce** [comment]
Testing confirmed SDL_Joystick PS devices use JoyButtonPressed to handle button presses.

**Comment by Scrubsauce** [comment]
PS-based SDL_Joystick triggers now register and set the values properly as of 6f960b4f648073f2b5b440f44ab73179f5beb712

Note- Since SDL_Joystick does not treat these as axes, for a device that fits this definition its triggers are limited to 0.0f (released) and 1.0f (pressed), intermediate values will not fire events in the SDL library for us to intercept in-code.

**Comment by Scrubsauce** [comment]
TODO:
- drop in/out #84 
- D-pad/hat events

**Comment by Scrubsauce** [comment]
D-pad/hat events for SDL_Joystick devices completed as of cc32ca911daa16a53c3187932033c6e184d07242

**Comment by Scrubsauce** [comment]
Split into #84
